# Site Build Settings

# Jekyll-paginate-v2 configuration
#  pagination:
#   enabled: true
#   per_page: 5
#   permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           '黑面包'
description:	       ''
author:              'heihei'
tupian:       

# 隐藏分享按钮
hide_post_share: true
# 隐藏相关内容
hide_related_posts: true
# 隐藏文章日期
hide_post_date: true
# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
  tabs:
    output: true
    sort_by: order 
